version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:2024.01.1
    steps:
      - checkout
      - run:
          name: check sudo
          command: sudo ls
      - run:
          command: sudo cat /etc/sudoers.d/circleci
